# Generated by Django 4.2.29 on 2026-04-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_options_student_answers_student_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='answers',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
