# Generated by Django 4.2.29 on 2026-04-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, default='OK', max_length=10),
        ),
    ]
